services:
  # Backend Service
  - type: web
    name: multiplayer-backend
    env: go
    region: singapore
    # Using explicit cd commands is safer if rootDir is ignored/missed
    buildCommand: cd backend && go build -o app .
    startCommand: cd backend && ./app
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: multiplayer-db
          property: connectionString

staticSites:
  # Frontend Service
  - type: static
    name: multiplayer-frontend
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: multiplayer-backend
          property: url

databases:
  # Postgres Database
  - name: multiplayer-db
    region: singapore
    databaseName: gamedb
    user: user

version: "1"
